"""encuentros y asistencia

Revision ID: 755eeba157b5
Revises: db52086735f2
Create Date: 2026-05-20 15:00:28.977178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755eeba157b5'
down_revision = 'db52086735f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encuentro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tema', sa.String(length=300), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrante_id', sa.Integer(), nullable=False),
    sa.Column('encuentro_id', sa.Integer(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['encuentro_id'], ['encuentro.id'], ),
    sa.ForeignKeyConstraint(['integrante_id'], ['integrante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencia')
    op.drop_table('encuentro')
    # ### end Alembic commands ###
