"""campos premium usuario

Revision ID: b76279b776d3
Revises: b8adaf2a8f7f
Create Date: 2026-06-12 11:36:11.805108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76279b776d3'
down_revision = 'b8adaf2a8f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombres', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('foto')
        batch_op.drop_column('telefono')
        batch_op.drop_column('correo')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombres')

    # ### end Alembic commands ###
