"""inicio limpio

Revision ID: db52086735f2
Revises: 
Create Date: 2026-05-20 14:50:37.613909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db52086735f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('alergia', sa.String(length=200), nullable=True),
    sa.Column('acudiente', sa.String(length=150), nullable=False),
    sa.Column('nombre_acudiente', sa.String(length=150), nullable=False),
    sa.Column('telefono_acudiente', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrante')
    # ### end Alembic commands ###
