"""notas privadas encuentros

Revision ID: e0dc9bb33afe
Revises: 1d0a5568049e
Create Date: 2026-06-05 09:25:28.999730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dc9bb33afe'
down_revision = '1d0a5568049e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encuentro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas_privadas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encuentro', schema=None) as batch_op:
        batch_op.drop_column('notas_privadas')

    # ### end Alembic commands ###
